name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install client dependencies
        run: npm install
        working-directory: ./client

      - name: Run biome check on client
        run: npm run biome:check
        working-directory: ./client

      - name: Install server dependencies
        run: npm install
        working-directory: ./api

      - name: Run biome check on api
        run: npm run check
        working-directory: ./api

